### ISSUE TITLE
Allow use with rails4

### ISSUE THREAD

**Issue by seanwalbran** [ernie/valium#13]
Adjust the version-checking logic to allow use of this gem with rails 4+:

https://gist.github.com/4582011

**Comment by schmurfy** [comment]
by the looks of it the pluck() method in rails 4 is now an equivalent to valium values_of.

**Comment by mat813** [comment]
Pluck can only take one argument, values_of can take more than one :-)

**Comment by schmurfy** [comment]
not anymore, in rails 4 pluck can take more than one ;)
It took time but they finally realized one argument was not that useful as it seems.

**Comment by mat813** [comment]
Ah, I'll have to do some s/values_of/pluck/ then :-)
