### ISSUE TITLE
Alias #values_of to #plucks and #value to #pluck

### ISSUE THREAD

**Issue by krainboltgreene** [ernie/valium#15]
ActiveRecord has a similar method called #pluck, and there's really no need for both, especially since #pluck only handles 1 argument.

**Comment by ernie** [comment]
I'm not going to clobber the AR method, even if I do wish pluck was implemented via Valium. This is unnecessary.

**Comment by krainboltgreene** [comment]
Alright, I'm going to fork valium, add it, and release it as "plucked" with
a few refactors and hstore support.

Thanks for looking at the issue.

On Mon, May 20, 2013 at 3:54 AM, Ernie Miller notifications@github.comwrote:

> I'm not going to clobber the AR method, even if I do wish pluck was
> implemented via Valium. This is unnecessary.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ernie/valium/issues/15#issuecomment-18141813
> .

## 

Kurtis Rainbolt-Greene, Hacker
Software Developer
612 S. Flower St.
Los Angeles, CA, 90017

**Comment by ernie** [comment]
@krainboltgreene best of luck if you decide to do so, but as someone who's done his fair share of overriding stock AR behavior in gems, I'd recommend against it. It'll lead to a world of hurt down the line, and bogus issues galore. There's a reason I immediate responded with "no." :)

**Comment by ernie** [comment]
Particularly since in more recent AR versions, pluck does in fact support multiple values.

**Comment by avdi** [comment]
Seems like an awfully trivial reason to fork. Not to mention that monkeypatching pre-existing methods from other libraries is the worst form of monkeypatching.
