### ISSUE TITLE
undefined method `empty?' for has_one AR relation

### ISSUE THREAD

**Issue by dibson** [ernie/valium#4]
Using:
- REE 1.8.7
- Rails 3.0.9
- Valium 0.3.0

I added Valium to my gem file, bundle installed, and ran my spec.  No changes to my codebase yet, and I'm getting lots of undefined method 'empty?' errors.

The error is raised when I save a user object - it fails on several has_one relations.  In the trace below, the relation is to the EmailNotification model.

I imagine it could be a a conflict with another gem - we have meta_where v1.0.4 also installed (among a handful of others).  Let me know if you could use more info, and thanks for the hard work you've already done!

```
 Failure/Error: @user.save
 undefined method `empty?' for "#<EmailNotification:0x1068eaa88>":EmailNotification
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/associations/association_proxy.rb:216:in `method_missing'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/valium-0.3.0/lib/valium.rb:96:in `[]'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/autosave_association.rb:337:in `save_has_one_association'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/autosave_association.rb:169:in `autosave_associated_records_for_email_pref'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activesupport-3.0.9/lib/active_support/callbacks.rb:434:in `_run_save_callbacks'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/callbacks.rb:273:in `create_or_update'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/persistence.rb:40:in `save'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/validations.rb:43:in `save'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/attribute_methods/dirty.rb:21:in `save'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/transactions.rb:240:in `save'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/transactions.rb:292:in `with_transaction_returning_status'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/connection_adapters/abstract/database_statements.rb:139:in `transaction'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/transactions.rb:207:in `transaction'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/transactions.rb:290:in `with_transaction_returning_status'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/transactions.rb:240:in `save'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/transactions.rb:251:in `rollback_active_record_state!'
 # .../.rvm/gems/ree-1.8.7-2011.03@rails3/gems/activerecord-3.0.9/lib/active_record/transactions.rb:239:in `save'
 # path/to/rails_app/spec/models/activity_event_spec.rb:59
```

**Comment by ernie** [comment]
Try the previous version and let me know if that one works. Just added
the association stuff today, curious if that's what's doing it.

Sent from my iPhone

On Sep 7, 2011, at 9:27 PM, Dibson T Hoffweiler
reply@reply.github.com
wrote:

**Comment by dibson** [comment]
Thanks for the quick response.

v0.2.1 does not break any spec for us - I'm going to start implementing some value_of calls next.

Below is a gist with a test case that fails for me.  I don't know if it's a spec worth keeping, but maybe it's a jumping off point for you.

https://gist.github.com/1204209

**Comment by ernie** [comment]
Looking at your spec makes things more obvious for me -- thanks! Using [:id] in the context of a has_one wouldn't make much sense for Valium, since instantiating the single record and using its attribute reader (via the `[]` syntax that exists already for instances of ActiveRecord::Base) carries very little overhead on its own.

Still, it shouldn't raise an error like this. I'll see what I can do.

**Comment by jaylevitt** [comment]
This error apparently can pop up even when I'm not explicitly using valium.  For instance, I just executed some code that called `current_user.demographic.update_attribute`, and later `current_user.update_attribute`; I got the error.  At no time did I attempt to call valium's `[]` method on either model, though I did call it on an association on another model. The same code works as expected without valium bundled in.  `User` does `has_one :demographic`.

Backtrace: https://gist.github.com/1204842

**Comment by ernie** [comment]
Yup. Unfortunately, it appears that AR 3.0.x doesn't actually load the target explicitly, like AR 3.1.x does. This is AR's code in 3.0.x:

``` ruby
def save_has_one_association(reflection)
  if (association = association_instance_get(reflection.name)) && !association.target.nil? && !association.destroyed?
    autosave = reflection.options[:autosave]

    if autosave && association.marked_for_destruction?
      association.destroy
    else
      key = reflection.options[:primary_key] ? send(reflection.options[:primary_key]) : id
                                                                                  # vvv FAIL vvv
      if autosave != false && (new_record? || association.new_record? || association[reflection.primary_key_name] != key || autosave)
        association[reflection.primary_key_name] = key
        saved = association.save(:validate => !autosave)
        raise ActiveRecord::Rollback if !saved && autosave
        saved
      end
    end
  end
end
```

TBH, I'm at this point I'm half-tempted to just disable the [] sugar on associations, and force value_of in those cases... at least on non-3.1 apps.

**Comment by ernie** [comment]
Yup. Just removing the alias. More trouble than it's worth. Try 0.4.0. It shouldn't get in your way.

**Comment by jaylevitt** [comment]
Any chance we'll see the sugar return eventually for 3.1, or is it brittle even there?

**Comment by ernie** [comment]
I'd rather see the syntax remain consistent across versions and let the user do the aliases if they want them.
