### ISSUE TITLE
Valium returns a nested array if an association collection is already loaded

### ISSUE THREAD

**Issue by gamov** [ernie/valium#8]
I have a Shipment with has_many :shipment_charges (that have a currency attribute).
```sh.shipment_charges.value_of :currency
=> ["USD", "USD", "USD", "SGD", "SGD"]

``````

Then I load the charges
```sh.shipment_charges
``````

I call value_of again:
```sh.shipment_charges.value_of :currency
=>[["USD"], ["USD"], ["USD"], ["SGD"], ["SGD"]]

```

My array is nested... I need to flatten it.

I checked the code and it's strange because it seems that you hit directly the DB. Maybe the cache sends you back directly an array when you are expecting a relation... something like that.
Since this gem is for performance purposes, it's a bit sad to have to call flatten each time.

Rails 3.0.11 / Ruby 1.9.2 / Valium 0.4
```

**Comment by ernie** [comment]
This is definitely a bug if it's happening. I'll try to work up a failing spec.

**Comment by ernie** [comment]
So, I can't seem to duplicate. Can you look at this spec and ensure it's testing what you're experiencing?

**Comment by gzigzigzeo** [comment]
Hello. This happens if association collection was previously set like so:

```
p = Person.first
p.widgets = [Widget.first, Widget.last]
puts p.widgets.value_of(:id).inspect # [[1], [100]]      
```

(Rails 3.1.3, Ruby 1.8.7)

I am now trying to make failing spec & fix.

**Comment by gzigzigzeo** [comment]
Here is the failing spec:
https://github.com/gzigzigzeo/valium/commit/643f1e8ff5882097d04d04abeccd9bc66146fa55

**Comment by gzigzigzeo** [comment]
It seems that problem is here (around line 95 at valium.rb):

  if loaded? && (empty? || args.all? {|a| first.attributes.has_key? a})
     to_a.map {|record| args.map {|a| record[a]}}
  else

**Comment by gzigzigzeo** [comment]
Thank you!

**Comment by gamov** [comment]
Thanks gzigzigzeo for the spec.
