### ISSUE TITLE
Chance to return hashes

### ISSUE THREAD

**Issue by masterkain** [ernie/valium#9]
It would be useful for me to benchmark how much I'll save when rendering JSON by instantiant AR objects vs raw Array.

`values_of` requires an array of attributes, we can return a _collection_ by mapping the arrays, like so:

```
[{:title => 'a', :artist => 'b'}, {:title => 'c', :artist => 'd'}]
```

More on subject: http://snippets.dzone.com/posts/show/302

Even if the conversion to Hash to JSON will be slow, at least I'd eliminate a pain point, the AR object instantiation for which the penalty is much greater than mapping the array as a collection of hashes.

Obviously it's something that I can do with the result, but I think it can be a nice addition to Valium.

**Comment by ernie** [comment]
Closing old issue. No sense diverging from pluck behavior in 4.x.
